### PR TITLE
Improve readme - Better to have the bash commands in a single line

### PR DESCRIPTION
**Pull request by miguelriemoliveira**
i @joao-pm-santos96 , If you have bash commands in a single line you may just click three times on top to select the complete bash command. 
If the command is mixed with teh text this is not possible, so always use a separate line for the bash commands ...

Check [rustbot](https://github.com/miguelriemoliveira/RustBot) for an exemple of a Readme.md.

### CODE REVIEW

**Comment by joao-pm-santos96** [comment]
Yes that's a nice addition! Didn't knew we could use ```bash. Will merge and update the rest of the file

**Comment by joao-pm-santos96** [comment]
Only one question: any reason for the code block you changed is being wrapped around ' '? I mean, I tried and if anything it gave less information in the terminal when running.. Is that something desired?

**Comment by miguelriemoliveira** [comment]
Hi @joao-pm-santos96 , no reason for the ''. 

It was just because I copy pasted from your readme. You should remove.

Concerning "```bash ... ```",  you can also use "```python ...  ```" or "```cpp ```". It is nice because it sintax highlights based on the language ...

Here's a cpp example: [](https://github.com/miguelriemoliveira/rws2019_moliveira/wiki/S1:-A-player-written-in-cpp).

**Comment by joao-pm-santos96** [comment]
That's cool! Understood both, thank you!

**Pull request merged**
